package com.demo.user;

import com.demo.base.BaseModel;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseModel<User> {
	public static final User dao = new User();

	public User findByUsername(String username) {
		return super.findFirst("select * from user where username = ?",
				username);
	}

	public User findByUser(String username, String password) {
		return super.findFirst(
				"select * from user where username = ? and password = ?",
				username, password);
	}
}
